name: 'Semantic Release'
description: 'A GitHub Action that will perform Semantic Release'
inputs:
  buildType:
    description: 'Type of build tool used in the project. E.g., maven, gradle, npm'
    required: true
    default: 'maven'
  devBranch:
    description: 'Name of the development branch'
    required: true
    default: 'main-release-dev'

runs:
  using: 'composite'
  steps:
  - run: |
        npm clean-install --force
        npm audit signatures
    shell: bash
    name: 'Install Dependencies'
    description: 'Install dependencies & Verify the integrity of provenance attestations and registry signatures for installed dependencies'
  - run: |
        if [ "${{ inputs.buildType }}" == "maven" ]; then
        npx semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch="${{inputs.devBranch}}" --skip-maven-deploy
        elif [ "${{ inputs.buildType }}" == "npm" ]; then
        npx semantic-release
        else
          echo "Invalid build type"
          exit 1
        fi 