image:
  # -- Image to use for deploying an application
  repository: "acrcfxsharedservices.azurecr.io/sd-factory-core/images/sd-factory"
  # -- Set the Image Pull Policy
  pullPolicy: Always
  # -- Image tage is defined in chart appVersion.
  # -- For PROD tag needs to be empty "" to be picked up from Chart.yaml
  tag: "main-06456a7"

imagePullSecrets: false

swagger_enabled: true

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  className: "nginx"
  host: "sdfactory.int.cofinity-x.com"
  hosts:
    - host: sdfactory.int.cofinity-x.com
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls: false

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

sdfactory:
  secret:
    jwkSetUri: "<path:sd-factory/data/idp#jwkSetUri>"
    clientId: "<path:sd-factory/data/idp#clientId>"
    clientSecret: "<path:sd-factory/data/idp#clientSecret>"
    authServerUrl: "<path:sd-factory/data/idp#auth-server-url>"
    realm: "<path:sd-factory/data/idp#realm>"
    resource: "<path:sd-factory/data/idp#resource>"
    custodianWalletUri: "<path:sd-factory/data/miw#uri>"
    clearingHouseUri: "<path:sd-factory/data/clearingHouse#uri>"
    clearingHouseServerUrl: "<path:sd-factory/data/clearingHouse#serverUrl>"
    clearingHouseRealm: "<path:sd-factory/data/clearingHouse#realm>"
    clearingHouseClientId: "<path:sd-factory/data/clearingHouse#clientId>"
    clearingHouseClientSecret: "<path:sd-factory/data/clearingHouse#clientSecret>"


# -- Pod resources requests and limits configuration
# -- Pod resources requests and limits configuration
resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 1024Mi

revocationService:
  baseUrlForCredentialList: "https://sd-factory-core.int.cofinity-x.com/api/credentials/"
  secret:
    jdbcurl: "<path:sd-factory-core/data/int/sd-factory-core-secrets#revocation-db-jdbc-url>"
