image:
  # -- Image to use for deploying an application
  repository: "ghcr.io/cofinity-x/cofinity-x-sd-factory-core/sdfactory"
  # -- Set the Image Pull Policy
  pullPolicy: Always
  # -- Image tage is defined in chart appVersion.
  # -- For PROD tag needs to be empty "" to be picked up from Chart.yaml
  tag: "latest"

imagePullSecrets:
  - name: "machineuser-pull-secret-ro"

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  className: "nginx"
  host: "sdfactory.cofinity-x.com"
  hosts:
    - host: sdfactory.cofinity-x.com
      paths:
        - path: /
          pathType: ImplementationSpecific


  tls:
    - tlsName: tls-secret
      hosts:
        - sdfactory.cofinity-x.com


service:
  type: ClusterIP
  port: 80
  targetPort: 8080

sdfactory:
  secret:
    jwkSetUri: "<path:essential-services/data/prod/custodian-prod#jwkSetUri>"
    clientId: "<path:essential-services/data/prod/custodian-prod#clientId>"
    clientSecret: "<path:essential-services/data/prod/custodian-prod#clientSecret>"
    authServerUrl: "<path:essential-services/data/prod/custodian-prod#auth-server-url>"
    realm: "<path:essential-services/data/prod/custodian-prod#realm>"
    resource: "<path:essential-services/data/prod/custodian-prod#resource>"
    custodianWalletUri: "<path:essential-services/data/prod/custodian-prod#uri>"
    clearingHouseUri: "<path:essential-services/data/prod/custodian-prod#clearingHouse-uri>"
    clearingHouseServerUrl: "<path:essential-services/data/prod/custodian-prod#clearingHouse-serverUrl>"
    clearingHouseRealm: "<path:essential-services/data/prod/custodian-prod#clearingHouse-realm>"
    clearingHouseClientId: "<path:essential-services/data/prod/custodian-prod#clearingHouse-clientId>"
    clearingHouseClientSecret: "<path:essential-services/data/prod/custodian-prod#clearingHouse-clientSecret>"


# -- Pod resources requests and limits configuration
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi

revocationService:
  baseUrlForCredentialList: "https://sd-factory-core.cofinity-x.com/api/credentials/"
  secret:
    jdbcurl: "<path:sd-factory-core/data/prod/sd-factory-core-secrets#revocation-db-jdbc-url>"